### PR TITLE
Remove bits with a specified size and sign

### PR DESCRIPTION
**Pull request by lukasberglund**
I changed the name of "doubles" to "float" since "float" seems more abstracted away from hardware and that is the path that our language is taking with this commit.

### CODE REVIEW

**Comment by lukasberglund** [comment]
@ayazhafiz  I'm getting a weird build fail on the hindent travis build. Can you take a look?

**Comment by ayazhafiz** [comment]
I think rebasing should do it

**Comment by lukasberglund** [comment]
Hey Ayaz, the Travis CI Pull Request isn't coming through, do you have an idea of how to fix it?

**Comment by ayazhafiz** [comment]
should be fixed!

**Comment by lukasberglund** [comment]
Niceeeee

**Pull request merged**
