### PR TITLE
Minor style changes 

### PR DESCRIPTION
**Pull request by lukasberglund**

### CODE REVIEW

**Comment by ayazhafiz** [comment]
What did you run over this? hlint and hspec? i think it would be worthwhile to add these to travis too.

**Comment by lukasberglund** [comment]
This was just me trying to get rid of brackets based on  [this styleguide](https://wiki.haskell.org/Programming_guidelines#Documentation).

**Comment by ayazhafiz** [comment]
Do you want to add [hindent](https://github.com/chrisdone/hindent) and [hlint](https://github.com/ndmitchell/hlint) as scripts and tests to the project? hlint will take care of a lot of the lint fixes, including remove extra parens as you mention.

**Comment by lukasberglund** [comment]
Yeah for sure.

**Comment by ayazhafiz** [comment]
@lukasberglund do you plan to add the linters?

**Comment by lukasberglund** [comment]
Yes. But I'm flying out tonight and want some time to chill. I'd do it monday

**Comment by lukasberglund** [comment]
Actually, how do I do that?

**Comment by ayazhafiz** [comment]
Add a script to .travis.yml that runs hindent/hlint over the haskell files in the entire project. Alternatively you can create a bash script and call the bash script from travis. If you would like an example, lmk.

**Comment by lukasberglund** [comment]
Could you give me one?

**Comment by ayazhafiz** [comment]
hindent (hindent.sh):

```bash
#!/bin/bash

hindent "$@" **/*.hs
```

`$@` passes all arguments passed to the command. So `./hident.sh --validate` would become `hindent --validate **/*.hs`.

hlint:

```
#!/bin/bash

hlint "$@" **/*.hs
```

You will have to install `hindent` and `hlint` via stack. You can specify this in the .travis.yml file.

**Pull request closed without merging**
